### ISSUE TITLE
Build log throwing InvalidOperationException

### ISSUE THREAD

**Issue by bording** [KirillOsenkov/MSBuildStructuredLog#136]
I'm using https://github.com/dotnet/project-system-tools to capture build logs. When viewing the design-time logs, everything is fine, but when I view a regular build log, I keep seeing the following:

![image](https://user-images.githubusercontent.com/753669/33055007-ee2ac5f6-ce4a-11e7-895f-6d93fc66a12d.png)

The exception is:
```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Build.Logging.StructuredLogger.MessageProcessor.AddCommandLine(TaskCommandLineEventArgs args) in C:\MSBuildStructuredLog\src\StructuredLogger\Construction\MessageProcessor.cs:line 408
   at Microsoft.Build.Logging.StructuredLogger.Construction.MessageRaised(Object sender, BuildMessageEventArgs args) in C:\MSBuildStructuredLog\src\StructuredLogger\Construction\Construction.cs:line 307
```

This log was created with Visual Studio 2017 15.4.4 using a new project created with the Console App (.NET Core) template.

[problem.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/1490048/problem.zip)

**Comment by bording** [comment]
Trying to open the file with a locally built debug build of the viewer reveals a bit more in the stack trace:

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Build.Logging.StructuredLogger.Target.GetTaskById(Int32 taskId) in C:\Code\MSBuildStructuredLog\src\StructuredLogger\ObjectModel\Target.cs:line 28
   at Microsoft.Build.Logging.StructuredLogger.MessageProcessor.AddCommandLine(TaskCommandLineEventArgs args) in C:\Code\MSBuildStructuredLog\src\StructuredLogger\Construction\MessageProcessor.cs:line 410
   at Microsoft.Build.Logging.StructuredLogger.MessageProcessor.Process(BuildMessageEventArgs args) in C:\Code\MSBuildStructuredLog\src\StructuredLogger\Construction\MessageProcessor.cs:line 111
   at Microsoft.Build.Logging.StructuredLogger.Construction.MessageRaised(Object sender, BuildMessageEventArgs args) in C:\Code\MSBuildStructuredLog\src\StructuredLogger\Construction\Construction.cs:line 307
```

**Comment by KirillOsenkov** [comment]
Thanks, I've fixed the symptom and it is now able to open the sample file you've attached.

I didn't deploy yet however, since I want to batch up a few more fixes before the release. If this is blocking you, you can clone the repo and build from source.

However what's really weird is that the logs are really wrong. They're too small for a proper .binlog file, they don't contain embedded source files, their tasks are incorrectly parented (not parented under targets at all, which breaks the invariant that I was relying on), and generally it seems like most stuff is missing.

@panopticoncentral have you seen this before?

**Comment by bording** [comment]
@KirillOsenkov I was just looking at the change you made, and yeah that does prevent exception, at the expense of losing the message in the output.

I had noticed that the log seemed to be missing a lot of detail, but I assumed that was related to the viewer not parsing something correctly, not that the log file itself was malformed. Interesting...

**Comment by panopticoncentral** [comment]
Hmm. I made a fix that was happening where the logging verbosity level wasn't turned up high enough for the logger, but that should be in the version you have. Can you try setting your logging level to "Verbose" in Tools|Options and see if you get a full build log?

**Comment by bording** [comment]
@panopticoncentral That seems to be the problem. I tried setting the verbosity to Diagnostic (because there is no Verbose in the dropdown), and that seems to stop the log files from throwing exceptions.

So it appears that there is still a bug around setting the log levels as needed for the logger.

Out of curiosity, which of the two VS options should be relevant for this?

![image](https://user-images.githubusercontent.com/753669/33287436-a69c9084-d386-11e7-843c-ee34e1212fa4.png)

It seems that if I set either of them to a higher level, then I get a correct binlog, which I wasn't expecting.

**Comment by KirillOsenkov** [comment]
As far as I know the bottom one is only relevant for C++. I think @panopticoncentral relies on the top setting?

**Comment by bording** [comment]
I can definitely leave the top one at Normal and change the bottom one to Diagnostic and see the binlog output change, fixing the problem.

The same thing happens if I change the top option to Diagnostic and leave the bottom one set to Minimal: the binlog outputs correctly.

**Comment by bording** [comment]
@panopticoncentral Should a file a new issue on https://github.com/dotnet/project-system-tools about this?
