### ISSUE TITLE
Errors reading binlog

### ISSUE THREAD

**Issue by onovotny** [KirillOsenkov/MSBuildStructuredLog#139]
I'm getting tons of errors like this:

```
System.InvalidOperationException: Sequence contains no matching element

   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)

   at Microsoft.Build.Logging.StructuredLogger.MessageProcessor.AddMessage(LazyFormattedBuildEventArgs args, String message) in C:\MSBuildStructuredLog\src\StructuredLogger\Construction\MessageProcessor.cs:line 194

   at Microsoft.Build.Logging.StructuredLogger.Construction.MessageRaised(Object sender, BuildMessageEventArgs args) in C:\MSBuildStructuredLog\src\StructuredLogger\Construction\Construction.cs:line 307
```

**Comment by onovotny** [comment]
Looks like a dup of #136. got latest and it works.

**Comment by bording** [comment]
@onovotny Note that while the latest version fixes the errors, that means your log file is missing information: https://github.com/dotnet/project-system-tools/issues/34

**Comment by onovotny** [comment]
Yeah, I see missing info :(
