### ISSUE TITLE
Crash when reading a log

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#154]
Reported by @dannyvv

=====

```
I tried to use the viewer on roslyn.
I just got a crash in the structured log viewer:
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 67
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.ReadNode() in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 73
   at Microsoft.Build.Logging.StructuredLogger.BinaryLogReader.Read(String filePath) in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BinaryLogReader.cs:line 27
   at Microsoft.Build.Logging.StructuredLogger.Serialization.Read(String filePath) in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Serialization.cs:line 80
   at StructuredLogViewer.HostedBuild.<>c__DisplayClass6_0.<BuildAndGetResult>b__0() in C:\MSBuildStructuredLog\src\StructuredLogViewer\HostedBuild.cs:line 64
```

Repro:
                Clone roslyn
                Git checkout origin/dev15.5.x
                Restore.cmd
                Open Developer commnd prompt
                Msbuild roslyn.sln
                Install structured logger from website
                Chose project/solution
                Poitn to roslyn.sln
                Wait a LONG time 😊
Result:
                Error reported:
 
                
Probably they need some magic env vars to work so I’ll try to build the .bl file externally.

**Comment by zsd4yr** [comment]
Hey Kirill! I am getting a similar issue

```
Error when reading the file: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.Build.Logging.StructuredLogger.BuildEventArgsReader.ReadBuildEventArgsFields() in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BuildEventArgsReader.cs:line 628
   at Microsoft.Build.Logging.StructuredLogger.BuildEventArgsReader.ReadBuildMessageEventArgs() in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BuildEventArgsReader.cs:line 463
   at Microsoft.Build.Logging.StructuredLogger.BuildEventArgsReader.Read() in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BuildEventArgsReader.cs:line 95
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 78
```

Why was this one closed out? I think my issue might be similar to https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/165 as I have a MASSIVE binary log
