### ISSUE TITLE
Error while analyzing build - System.InvalidCastException: Unable to cast object of type 'Microsoft.Build.Logging.StructuredLogger.Folder' to type 'Microsoft.Build.Logging.StructuredLogger.Project'.

### ISSUE THREAD

**Issue by paulomorgado** [KirillOsenkov/MSBuildStructuredLog#212]
```
Error while analyzing build. Sorry about that. Please Ctrl+C to copy this text and file an issue on https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new 

System.InvalidCastException: Unable to cast object of type 'Microsoft.Build.Logging.StructuredLogger.Folder' to type 'Microsoft.Build.Logging.StructuredLogger.Project'.

   at Microsoft.Build.Logging.StructuredLogger.ImportTreeAnalyzer.AddImport(Message message, String project, String importedProject, Int32 line, Int32 column, Boolean imported, String reason)
   at Microsoft.Build.Logging.StructuredLogger.ImportTreeAnalyzer.VisitMessage(Message message, StringCache stringTable)
   at Microsoft.Build.Logging.StructuredLogger.TreeNode.VisitAllChildren[T](Action`1 processor, CancellationToken cancellationToken, Boolean takeChildrenSnapshot)
   at Microsoft.Build.Logging.StructuredLogger.TreeNode.VisitAllChildren[T](Action`1 processor, CancellationToken cancellationToken, Boolean takeChildrenSnapshot)
   at Microsoft.Build.Logging.StructuredLogger.ImportTreeAnalyzer.Analyze(Folder evaluation, StringCache stringTable)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.ProcessBeforeChildrenVisited(TreeNode node)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Analyze()
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeBuild(Build build)


```

**Comment by KirillOsenkov** [comment]
Hey Paulo, any chance you could email me your .binlog? Don't email it to me if the environment variables contain any information you wouldn't like me to see. Of course I'll treat it confidentially and will delete it as soon as I'm done with the investigation. kirill.osenkov at microsoft.

**Comment by KirillOsenkov** [comment]
I'm guessing your MSBuild language is Portuguese? In that case I kind of have a guess of what might be going wrong. Non-english logs are not really supported yet, but at least the viewer shouldn't crash.

**Comment by KirillOsenkov** [comment]
Never mind, I pushed a blind fix. I think it should fix it for you. Start the viewer and wait for it to update to 2.0.50, then restart again.

**Comment by daveaglick** [comment]
YOLO fixes are best fixes

**Comment by paulomorgado** [comment]
Fixed!

**Comment by KirillOsenkov** [comment]
Thanks to Paulo's log I have now pushed an even better fix! Found the real problem and solved it. Details here: https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/bd4d73b5116d09fdaf2b90e31a5e08668634281f
