### ISSUE TITLE
Error while analyzing build

### ISSUE THREAD

**Issue by powercode** [KirillOsenkov/MSBuildStructuredLog#227]
v 2.0.61

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Logging.StructuredLogger.CompilationWrites.TryParse(Task task)
   at Microsoft.Build.Logging.StructuredLogger.ManagedCompilerTask.get_CompilationWrites()
   at Microsoft.Build.Logging.StructuredLogger.DoubleWritesAnalyzer.AnalyzeTask(Task task)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeTask(Task task)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Analyze()
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeBuild(Build build)
```

**Comment by KirillOsenkov** [comment]
Thanks, fixed in 2.0.64.
