### ISSUE TITLE
Preprocess command crashes the app

### ISSUE THREAD

**Issue by AArnott** [KirillOsenkov/MSBuildStructuredLog#238]
Repro steps:

```
dotnet new classlib -o cl
cd cl
msbuild /bl
.\msbuild.binlog
```

Then right-click on the project in the tree and click the Preprocess command.

The app vanishes. Event Viewer shows this crashing callstack:

```
Application: StructuredLogViewer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at StructuredLogViewer.Controls.TextViewerControl..ctor()
   at StructuredLogViewer.Controls.DocumentWell.DisplaySource(System.String, System.String, Int32, Int32, System.Action, Boolean)
   at StructuredLogViewer.Controls.BuildControl.DisplayFile(System.String, Int32, Int32)
   at StructuredLogViewer.Controls.BuildControl.<.ctor>b__29_10(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at StructuredLogViewer.Entrypoint.Main(System.String[])
```

**Comment by KirillOsenkov** [comment]
Any chance you could do this under debugger and tell me which file is not found? I can't repro locally.

What's the app version? Should be 2.0.68.

**Comment by KirillOsenkov** [comment]
I think the easiest would be for you to clone the source and F5 so it's easier to debug. Maybe even submit a PR if it's something trivial!

**Comment by AArnott** [comment]
The app version is 1.2.12. But it's not offering an upgrade.

**Comment by AArnott** [comment]
I coerced an upgrade by installing the latest version from your readme file.
It works now. Thanks!
