### ISSUE TITLE
InvalidCastException - MBL.StructuredLogger.Property to type MBL.StructuredLogger.TreeNode

### ISSUE THREAD

**Issue by InKahootz** [KirillOsenkov/MSBuildStructuredLog#242]
Doing some building in the [corefx](http://github.com/dotnet/corefx) repo. Specifically I'm building in the src/System.Collections/src folder.

```msbuild /t:Rebuild /logger:StructuredLogger,"C:\Users\Hank\AppData\Local\MSBuildStructuredLogViewer\app-2.0.64\StructuredLogger.dll";"C:\Users\Hank\Desktop\system.collections.structuredlog" /bl:"C:\Users\Hank\Desktop\system.collections.binlog"```

I can open the default binlog just fine however the structuredlog errors out.
```
System.InvalidCastException: Unable to cast object of type 'Microsoft.Build.Logging.StructuredLogger.Property' to type 'Microsoft.Build.Logging.StructuredLogger.TreeNode'.
   at Microsoft.Build.Logging.StructuredLogger.BuildLogReader.ReadNode()
   at Microsoft.Build.Logging.StructuredLogger.BuildLogReader.ReadNode()
   at Microsoft.Build.Logging.StructuredLogger.BuildLogReader.ReadNode()
   at Microsoft.Build.Logging.StructuredLogger.BuildLogReader.ReadNode()
   at Microsoft.Build.Logging.StructuredLogger.BuildLogReader.Read(Stream stream, Byte[] projectImportsArchive)
   at Microsoft.Build.Logging.StructuredLogger.BuildLogReader.Read(String filePath)
   at Microsoft.Build.Logging.StructuredLogger.Serialization.Read(String filePath)
   at StructuredLogViewer.MainWindow.<>c__DisplayClass23_0.<OpenLogFile>b__0()
```
Here are both of the logs I output.

[system.collections.structuredlog.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/2981430/system.collections.structuredlog.zip)
[system.collections.binlog.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/2981429/system.collections.binlog.zip)

I just changed the filename of the structured one so you tell them apart.

Thanks for your work!

**Comment by KirillOsenkov** [comment]
Lol you've uncovered a funny case! Thanks! I will deploy the fix shortly.
