### ISSUE TITLE
ArgumentOutOfRangeException during Preprocess on project

### ISSUE THREAD

**Issue by RikkiGibson** [KirillOsenkov/MSBuildStructuredLog#258]
Version used: 2.0.109

Analyzing a build on a very simple netcoreapp3.0 console app project, can provide more details or a reproducer repo if needed. I right-clicked a "Project" element, clicked "Preprocess" and got the below error:

---------------------------
Unexpected exception. Sorry about that.

Please Ctrl+C to copy this text and file an issue at https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)

   at System.SZArrayHelper.get_Item[T](Int32 index)

   at StructuredLogViewer.PreprocessedFileManager.CorrectForMultilineImportElement(SourceText text, Int32 lineNumber)

   at StructuredLogViewer.PreprocessedFileManager.GetPreprocessedText(String sourceFilePath)

   at StructuredLogViewer.PreprocessedFileManager.GetPreprocessedText(String sourceFilePath)

   at StructuredLogViewer.PreprocessedFileManager.ShowPreprocessed(String sourceFilePath)

   at StructuredLogViewer.Controls.BuildControl.<.ctor>b__34_13(Object s, RoutedEventArgs a)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by KirillOsenkov** [comment]
any chance you could share the .binlog? Feel free to email privately at my first name dot last name at Microsoft. Or in any other way that is convenient to you. Thanks!

**Comment by RikkiGibson** [comment]
Done, thanks!

**Comment by KirillOsenkov** [comment]
Thanks. For some reason the log contains null text for some embedded files, such as `C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props`

**Comment by KirillOsenkov** [comment]
I've published 2.0.112 which at least doesn't crash when you try to preprocess in this situation. If you file an MSBuild bug, would you paste the link here? I'll then close this issue.

**Comment by KirillOsenkov** [comment]
@RikkiGibson did you get a chance to file an MSBuild issue?

**Comment by RikkiGibson** [comment]
Thanks for the reminder. I will make sure to do this soon.

**Comment by nguerrera** [comment]
I will file the issue.

**Comment by nguerrera** [comment]
Filed https://github.com/microsoft/msbuild/issues/4714

**Comment by KirillOsenkov** [comment]
This is all fixed now.
