### ISSUE TITLE
Exception on opening binlog

### ISSUE THREAD

**Issue by Inirit** [KirillOsenkov/MSBuildStructuredLog#274]
When opening a binlog file I get an error message box with the stack trace below. Dismissing the error results in the app getting stuck on the "Rendering tree..." progress bar indefinitely.

According to the start page, I'm using version 2.0.159 which I believe is the latest available. Unfortunately I cannot provide a copy of the particular binlogs I'm trying to open, though I can try to provide additional details if needed.

```
System.ArgumentNullException: Value cannot be null.

Parameter name: key

   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)

   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)

   at StructuredLogViewer.PreprocessedFileManager.GetOrCreateImportMap(String projectFilePath)

   at StructuredLogViewer.PreprocessedFileManager.VisitImport(Import import, Project projectEvaluationContext)

   at StructuredLogViewer.PreprocessedFileManager.<>c__DisplayClass8_0.<BuildImportMap>b__0(Import import)

   at Microsoft.Build.Logging.StructuredLogger.TreeNode.VisitAllChildren[T](Action`1 processor, CancellationToken cancellationToken, Boolean takeChildrenSnapshot)

   at Microsoft.Build.Logging.StructuredLogger.TreeNode.VisitAllChildren[T](Action`1 processor, CancellationToken cancellationToken, Boolean takeChildrenSnapshot)

   at StructuredLogViewer.PreprocessedFileManager.BuildImportMap()

   at StructuredLogViewer.PreprocessedFileManager..ctor(Build build, SourceFileResolver sourceFileResolver)

   at StructuredLogViewer.Controls.BuildControl..ctor(Build build, String logFilePath)

   at StructuredLogViewer.MainWindow.DisplayBuild(Build build)

   at StructuredLogViewer.MainWindow.<OpenLogFile>d__27.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by BihtSift** [comment]
I was getting this as well.  For us it was happening when we were using an older binlog .dll with msbuild 15.0.  Passing msbuild /bl fixed it for us.

**Comment by KirillOsenkov** [comment]
I've hardened the viewer against this situation so hopefully these binlogs will open now. Unfortunately I can't confirm myself since I don't have the binlogs.

If anyone has a binlog they can share with me privately, that would help a lot because I still don't understand the issue. You can e-mail it to kirill dot osenkov at microsoft dot com.

**Comment by Inirit** [comment]
I've updated to version 2.0.161 and can confirm (at least for me) that the guard worked.

**Comment by KirillOsenkov** [comment]
If it’s not too difficult, and you can find a repro, I’d be interested to take a look. But don’t spend too much time on it, since we have a workaround.

**Comment by BihtSift** [comment]
Just to confirm, the update resolved it for us as well.  I can open the binlogs I have marked as broken just fine.

I'll try to get a repro case going if possible, but I can't send you my binlog as is unfortunately.

**Comment by KirillOsenkov** [comment]
You can download any release from the GitHub Releases page and try that. Or clone the repo, checkout the commit you want and build that.

**Comment by KirillOsenkov** [comment]
I'll close this issue but feel free to reopen or file a new one if you're still having problems.
