### ISSUE TITLE
Root element missing opening up a binary log

### ISSUE THREAD

**Issue by jaredpar** [KirillOsenkov/MSBuildStructuredLog#276]
Getting the following exception when I open up a binary log on my machine.

Binary log link: https://1drv.ms/u/s!Asdf6Q-OsHE7idRxSMAYv9cLL4_xgg?e=dqRtuv

```
---------------------------

---------------------------
Unexpected exception. Sorry about that.

Please Ctrl+C to copy this text and file an issue at https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new



System.Xml.XmlException: Root element is missing.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)

   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()

   at System.Xml.XmlTextReaderImpl.Read()

   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)

   at System.Xml.XmlDocument.Load(XmlReader reader)

   at System.Xml.XmlDocument.LoadXml(String xml)

   at StructuredLogViewer.Controls.BuildControl.<GetTargets>d__50.MoveNext()

   at StructuredLogViewer.Controls.BuildControl.AddSourceFile(Folder folder, String filePath, String[] parts, Int32 index)

   at StructuredLogViewer.Controls.BuildControl.AddSourceFile(Folder folder, String filePath, String[] parts, Int32 index)

   at StructuredLogViewer.Controls.BuildControl.AddSourceFile(Folder folder, String filePath, String[] parts, Int32 index)

   at StructuredLogViewer.Controls.BuildControl.AddSourceFile(Folder folder, String filePath, String[] parts, Int32 index)

   at StructuredLogViewer.Controls.BuildControl.AddSourceFile(Folder folder, String filePath, String[] parts, Int32 index)

   at StructuredLogViewer.Controls.BuildControl.AddSourceFile(Folder folder, String filePath, String[] parts, Int32 index)

   at StructuredLogViewer.Controls.BuildControl.AddSourceFile(Folder folder, String filePath, String[] parts, Int32 index)

   at StructuredLogViewer.Controls.BuildControl.AddSourceFile(Folder folder, String filePath, String[] parts, Int32 index)

   at StructuredLogViewer.Controls.BuildControl.AddSourceFile(Folder folder, String filePath, String[] parts, Int32 index)

   at StructuredLogViewer.Controls.BuildControl.AddSourceFile(Folder folder, String filePath, String[] parts, Int32 index)

   at StructuredLogViewer.Controls.BuildControl.PopulateFilesTab()

   at StructuredLogViewer.Controls.BuildControl..ctor(Build build, String logFilePath)

   at StructuredLogViewer.MainWindow.DisplayBuild(Build build)

   at StructuredLogViewer.MainWindow.<OpenLogFile>d__27.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------
 
```

**Comment by KirillOsenkov** [comment]
@jaredpar Your file `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Microsoft.Common.targets\ImportAfter\Microsoft.Web.ImportAfter.targets` is strangely corrupted and consists of 1013 zero bytes.

I've hardened the viewer against this case to be able to open such files but you should see how it got into such a weird state.

**Comment by KirillOsenkov** [comment]
Fixed in https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/76983110cad86a3d5154a89045914bb52837886a

will publish an updated viewer soon

**Comment by jaredpar** [comment]
Yep that file did appear to be busted. I had to repair Visual Studio to get it working again.
