### ISSUE TITLE
OOM Exception

### ISSUE THREAD

**Issue by OdeToCode** [KirillOsenkov/MSBuildStructuredLog#282]
Built this repo from current master branch. Tried to open the binary log produced by the aspnet/AspNetCore build. Log file available here: https://www.dropbox.com/s/c24tpyitillwrqy/Build.binlog?dl=0

```
---------------------------

---------------------------
Unexpected exception. Sorry about that.

Please Ctrl+C to copy this text and file an issue at https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new



System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

   at System.Windows.Threading.DispatcherSynchronizationContext.CreateCopy()

   at System.Threading.ExecutionContext.Capture(StackCrawlMark& stackMark, CaptureOptions options)

   at System.Threading.ExecutionContext.Capture()

   at MS.Internal.CulturePreservingExecutionContext..ctor()

   at MS.Internal.CulturePreservingExecutionContext.Capture()

   at System.Windows.Threading.Dispatcher.LegacyBeginInvokeImpl(DispatcherPriority priority, Delegate method, Object args, Int32 numArgs)

   at System.Windows.Media.MediaContext.ScheduleNextRenderOp(TimeSpan minimumDelay)

   at System.Windows.Media.MediaContext.NotifyPresented(MIL_PRESENTATION_RESULTS presentationResults, Int64 presentationTime, Int32 displayRefreshRate)

   at System.Windows.Media.MediaContext.NotifyChannelMessage()

   at System.Windows.Media.MediaContextNotificationWindow.MessageFilter(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------
```

**Comment by KirillOsenkov** [comment]
Try switching to 64-bit? I think it might have Prefer32Bit somewhere??

**Comment by KirillOsenkov** [comment]
Ah, yes, just delete this line: https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/eda3a98d1523670c02f43b6bbef7c59cc28c06ca/src/StructuredLogViewer/StructuredLogViewer.csproj#L10

**Comment by KirillOsenkov** [comment]
I don’t remember why it’s there. Sorry about the friction. Please continue filing issues, I want to make sure you have a great experience with the tool.

**Comment by OdeToCode** [comment]
No worries, I should have spotted that myself. In any case, once the process launched as 64bit, everything works and loads.
