### ISSUE TITLE
Crashes on F# solution

### ISSUE THREAD

**Issue by josiahdj** [KirillOsenkov/MSBuildStructuredLog#309]
---------------------------

---------------------------
Unexpected exception. Sorry about that.

Please Ctrl+C to copy this text and file an issue at https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new

System.NullReferenceException: Object reference not set to an instance of an object.

   at StructuredLogViewer.Core.ProjectGraph.MsaglProjectGraphConstructor.ComputeCommonGlobalProperties(RuntimeGraph runtimeGraph) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\ProjectGraph\MSAGLProjectGraphConstructor.cs:line 152

   at StructuredLogViewer.Core.ProjectGraph.MsaglProjectGraphConstructor.FromBuild(Build build) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\ProjectGraph\MSAGLProjectGraphConstructor.cs:line 61

   at StructuredLogViewer.Controls.BuildControl.PopulateProjectGraph() in C:\MSBuildStructuredLog\src\StructuredLogViewer\Controls\BuildControl.xaml.cs:line 265

   at StructuredLogViewer.Controls.BuildControl..ctor(Build build, String logFilePath) in C:\MSBuildStructuredLog\src\StructuredLogViewer\Controls\BuildControl.xaml.cs:line 204

   at StructuredLogViewer.MainWindow.DisplayBuild(Build build) in C:\MSBuildStructuredLog\src\StructuredLogViewer\MainWindow.xaml.cs:line 560

   at StructuredLogViewer.MainWindow.<BuildCore>d__34.MoveNext() in C:\MSBuildStructuredLog\src\StructuredLogViewer\MainWindow.xaml.cs:line 495

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by KirillOsenkov** [comment]
@cdmihai

**Comment by KirillOsenkov** [comment]
@josiahdj any chance you could share the .binlog that fails with me privately? My first name dot last name at microsoft dot com.

I tried building an F# project but I can't repro this.

@cdmihai I've fixed one nullref recently where GlobalProperties was null. Do you think it is what's null here?

**Comment by KirillOsenkov** [comment]
I've published 2.1.57 with a hope to fix this. Care to give the new version a try?

Update by just starting the viewer from the Start menu, wait for it to auto-update, then restart again.

**Comment by KirillOsenkov** [comment]
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/c3ad099a6e1afc1cd635b3eaabcfe3c0296c2318

**Comment by josiahdj** [comment]
It wasn't a log file, it was an F# solution.

**Comment by josiahdj** [comment]
FWIW, the new version doesn't crash anymore. Thanks!
