### ISSUE TITLE
Attempting to Build With Invalid MSBuild Switch Yields "File Not Found" Error

### ISSUE THREAD

**Issue by aolszowka** [KirillOsenkov/MSBuildStructuredLog#313]
I am trying to debug the /graph switch to understand why our third party extensions to MSBuild are not being built. Using MSBuildStructuredLog I was hoping to get some insight.

Attempting to build out of the box with the following switches yielded an error:

![image](https://user-images.githubusercontent.com/2592881/75926703-38a10180-5e28-11ea-8847-1b854fea3856.png)

```
System.IO.FileNotFoundException: Could not find file 'C:\Users\imageuser\AppData\Local\Temp\MSBuildStructuredLog-54888.buildlog'.
File name: 'C:\Users\imageuser\AppData\Local\Temp\MSBuildStructuredLog-54888.buildlog'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Build.Logging.StructuredLogger.Serialization.DetectLogFormat(String filePath) in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Serialization.cs:line 94
   at Microsoft.Build.Logging.StructuredLogger.Serialization.Read(String filePath) in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Serialization.cs:line 78
   at StructuredLogViewer.HostedBuild.<>c__DisplayClass5_0.<BuildAndGetResult>b__0() in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\HostedBuild.cs:line 49
```

I have since tracked this down to the fact that `/graph` is not supported by the version of MSBuild being used. Switching to a supported version of MSBuild appears to have resolved the issue.

The error message is very misleading, but I am not sure if there is a better way to handle this situation. It maybe a corner case not worth exploring.

**Comment by KirillOsenkov** [comment]
yes MSBuild 14 and below are no longer supported. I need to remove them from the combo box

**Comment by KirillOsenkov** [comment]
Fixed in https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/61585324e08ff3dca58a246c27cb21e19e1763d0
