### ISSUE TITLE
Feature request - add Save SubTree option to the node popup menu.

### ISSUE THREAD

**Issue by MarkKharitonov** [KirillOsenkov/MSBuildStructuredLog#418]
Suppose I want to analyze a subtree. I sometime copy it and paste in Notepad++, because I could then leverage search in Notepad++, which is more powerful than the built-in search.

However, this does not work well for very large subtrees:
```
Unexpected exception. Sorry about that.

Please Ctrl+C to copy this text and file an issue at https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at ICSharpCode.AvalonEdit.Highlighting.HtmlClipboard.CreateHtmlFragment(IDocument document, IHighlighter highlighter, ISegment segment, HtmlOptions options)
   at ICSharpCode.AvalonEdit.Editing.Selection.CreateHtmlFragment(HtmlOptions options)
   at ICSharpCode.AvalonEdit.Editing.Selection.CreateDataObject(TextArea textArea)
   at ICSharpCode.AvalonEdit.Editing.EditingCommandHandler.CopySelectedText(TextArea textArea)
   at ICSharpCode.AvalonEdit.Editing.EditingCommandHandler.OnCopy(Object target, ExecutedRoutedEventArgs args)
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at StructuredLogViewer.Controls.TextViewerControl.copyMenu_Click(Object sender, RoutedEventArgs e) in C:\MSBuildStructuredLog\src\StructuredLogViewer\Controls\TextViewerControl.xaml.cs:line 264
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Having this option solves the problem.

**Comment by KirillOsenkov** [comment]
I see, we should turn off copying Html formatting in the editor, just copy raw text.

**Comment by KirillOsenkov** [comment]
What are you missing from search? I'm guessing regex support?

**Comment by MarkKharitonov** [comment]
Three are many cases when Notepad++ helps.
For example, I want to search the search results. In notepad++ it is trivial - copy it to a new window and search.
Regex is another example.

Sometimes I want to compare two subtrees belonging to two different binary logs. Often it is not possible due to concurrent nature of the build, sometimes it is possible.

**Comment by KirillOsenkov** [comment]
I turned off copying Html with this commit:
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/7fd033faa8447649b73fb1fb9d265278667a6eb3

Could you please try it and see if you still see issues copying large text.

If that doesn't help, try using the Open in external editor button:
![image](https://user-images.githubusercontent.com/679326/102310893-bd28c080-3f20-11eb-955c-337155553ebf.png)

**Comment by KirillOsenkov** [comment]
I think between all this and Copy subtree/View subtree text context menu items we have this scenario well covered. But let me know if not.

**Comment by MarkKharitonov** [comment]
Thank you. Do I have to build from source?

**Comment by KirillOsenkov** [comment]
For now. I want to publish the latest batch in a few days to save people from updating needlessly.

**Comment by MarkKharitonov** [comment]
Seems to work fine. I copied a subtree with 77K lines without any problems.
