### ISSUE TITLE
NRE on exit from viewer

### ISSUE THREAD

**Issue by alexey-gusarov** [KirillOsenkov/MSBuildStructuredLog#430]
Hello
Viewer from rider:
AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\203.5981.141\tools\MSBuildStructuredLogViewer\StructuredLogViewer.exe
version: 2.1.196+aa83ca3442
Unfortunately I can't attach binlog

```
---------------------------

---------------------------
Unexpected exception. Sorry about that.

Please Ctrl+C to copy this text and file an issue at https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new



System.NullReferenceException: Object reference not set to an instance of an object.

   at StructuredLogViewer.Controls.TreeViewExtensions.<>c__1`1.<SelectContainerFromItem>b__1_1(ItemsControl container, SelectInfo`1 info) in C:\MSBuildStructuredLog\src\StructuredLogViewer\Controls\TreeViewExtensions.cs:line 57

   at StructuredLogViewer.Controls.TreeViewExtensions.SelectContainerFromItem[T](ItemsControl container, SelectInfo`1 selectInfo) in C:\MSBuildStructuredLog\src\StructuredLogViewer\Controls\TreeViewExtensions.cs:line 161

   at StructuredLogViewer.Controls.BuildControl.BuildControl_Loaded(Object sender, RoutedEventArgs e) in C:\MSBuildStructuredLog\src\StructuredLogViewer\Controls\BuildControl.xaml.cs:line 775

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)

   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)

   at MS.Internal.LoadedOrUnloadedOperation.DoWork()

   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()

   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()

   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)

   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

````

**Comment by KirillOsenkov** [comment]
Thanks, this is good enough.

**Comment by KirillOsenkov** [comment]
I added some null checks, hopefully this will go away.

I'm in the middle of a bunch of fixes but once I stabilize in a few days Rider should take a new snapshot.
