### ISSUE TITLE
TimeSpan overflowed because the duration is too long.

### ISSUE THREAD

**Issue by arthur-conde** [KirillOsenkov/MSBuildStructuredLog#431]
This exception came up while trying to view a log for a build where the duration exceeded 90 minutes. I'm trying to investigate why the build gets stuck _sometimes_.

```log
Error while analyzing build. Sorry about that. Please Ctrl+C to copy this text and file an issue on https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new 

System.OverflowException: TimeSpan overflowed because the duration is too long.
   at System.TimeSpan.Add(TimeSpan ts)
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeTask(Task task) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 220
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 74
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 76
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 76
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 76
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 76
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 76
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 76
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 76
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Analyze() in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 61
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeBuild(Build build) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 35
```

**Comment by KirillOsenkov** [comment]
I'm guessing we have the TaskStarted event but no TaskFinished event (because the task never finishes). I made sure Duration is non-negative. You can build the latest master yourself to verify, but I'm planning to ship an update within the next few days.
