### ISSUE TITLE
There is an NRE when trying to analyze the build 

### ISSUE THREAD

**Issue by hssea** [KirillOsenkov/MSBuildStructuredLog#446]
I'm trying to build a solution that has 97 projects, with a mix of projects targeting net472 and netstandard 2.0.  This is happening on a Windows 10 server (19042) and VS 2019 (16.8.4).

Things were working fine, before a Windows update that was pushed yesterday (02/09/21), but today, I began to hit the following error:

Error while analyzing build. Sorry about that. Please Ctrl+C to copy this text and file an issue on https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new 

System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeMessage(Message message) in C:\projects\msbuildstructuredlog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 120

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\projects\msbuildstructuredlog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 72

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\projects\msbuildstructuredlog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 80

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Analyze() in C:\projects\msbuildstructuredlog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 60

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeBuild(Build build) in C:\projects\msbuildstructuredlog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 34

**Comment by KirillOsenkov** [comment]
Is there any sensitive data in your binlog? Any chance you can email it to me at my first name dot last name at microsoft? It will be treated confidentially and deleted as soon as I understand what's going on. Thanks.

**Comment by KirillOsenkov** [comment]
Also, what version of the viewer are you using? You should be on 2.1.307. Use File -> Start Page to check.

**Comment by hssea** [comment]
I saw a message that I needed to restart the viewer, so it'd be on th elatest version.

Once I did it, the issue didn't repro anymore.  So I'll be closing this issue
