### ISSUE TITLE
Got error in MSBuildStructuredLogViewer

### ISSUE THREAD

**Issue by jmarolf** [KirillOsenkov/MSBuildStructuredLog#464]
Version:  2.1.364

Got the following error reading this file: 
[format.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/6214084/format.zip)

```
System.ArgumentNullException: Value cannot be null.

Parameter name: collection
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.Build.Logging.StructuredLogger.TreeNode.SortChildren() in C:\MSBuildStructuredLog\src\StructuredLogger\ObjectModel\TreeNode.cs:line 50
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.ProcessBeforeChildrenVisited(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 119
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 78
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 80
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Analyze() in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 64
   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeBuild(Build build) in C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:line 36
```

**Comment by KirillOsenkov** [comment]
Deployed in 2.1.370 thanks @jmarolf!
