### ISSUE TITLE
Error while analyzing build: An item with the same key has already been added.

### ISSUE THREAD

**Issue by kzu** [KirillOsenkov/MSBuildStructuredLog#51]
I'm seeing this error in one particular project build:

```
---------------------------

---------------------------
Error while analyzing build. Very sorry about that. Please Ctrl+C to copy this text and file an issue on https://github.com/KirillOsenkov/MSBuildStructuredLog 

System.ArgumentException: An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)

   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)

   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)

   at Microsoft.Build.Logging.StructuredLogger.CopyLocalAnalyzer.AnalyzeResolveAssemblyReference(Task rar)

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeTask(Task task)

   at Microsoft.Build.Logging.StructuredLogger.TreeNode.VisitAllChildren[T](Action`1 processor, CancellationToken cancellationToken) in C:\MSBuildStructuredLog\src\StructuredLogger\ObjectModel\TreeNode.cs:line 408

   at Microsoft.Build.Logging.StructuredLogger.TreeNode.VisitAllChildren[T](Action`1 processor, CancellationToken cancellationToken) in C:\MSBuildStructuredLog\src\StructuredLogger\ObjectModel\TreeNode.cs:line 420

   at Microsoft.Build.Logging.StructuredLogger.TreeNode.VisitAllChildren[T](Action`1 processor, CancellationToken cancellationToken) in C:\MSBuildStructuredLog\src\StructuredLogger\ObjectModel\TreeNode.cs:line 420

   at Microsoft.Build.Logging.StructuredLogger.TreeNode.VisitAllChildren[T](Action`1 processor, CancellationToken cancellationToken) in C:\MSBuildStructuredLog\src\StructuredLogger\ObjectModel\TreeNode.cs:line 420

   at Microsoft.Build.Logging.StructuredLogger.TreeNode.VisitAllChildren[T](Action`1 processor, CancellationToken cancellationToken) in C:\MSBuildStructuredLog\src\StructuredLogger\ObjectModel\TreeNode.cs:line 420

   at Microsoft.Build.Logging.StructuredLogger.TreeNode.VisitAllChildren[T](Action`1 processor, CancellationToken cancellationToken) in C:\MSBuildStructuredLog\src\StructuredLogger\ObjectModel\TreeNode.cs:line 420

   at Microsoft.Build.Logging.StructuredLogger.TreeNode.VisitAllChildren[T](Action`1 processor, CancellationToken cancellationToken) in C:\MSBuildStructuredLog\src\StructuredLogger\ObjectModel\TreeNode.cs:line 420

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Analyze()

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeBuild(Build build)
---------------------------
OK   
---------------------------
```

Just following the instruction message and reporting :)

**Comment by kzu** [comment]
:+1:!

**Comment by KirillOsenkov** [comment]
Thanks, I've deployed an update. It'd be interesting to see the build log file if possible of that project which makes this happen. It would mean that two RAR outputs are exactly the same and I'm curious when this can happen.
