### ISSUE TITLE
Loading binlog causes 'Sequence contains more than one element' in 2.1.525

### ISSUE THREAD

**Issue by Eilon** [KirillOsenkov/MSBuildStructuredLog#526]
```
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.Build.Logging.StructuredLogger.Construction.TargetSkipped(TargetSkippedEventArgs2 args) in C:\MSBuildStructuredLog\src\StructuredLogger\Construction\Construction.cs:line 321
   at Microsoft.Build.Logging.StructuredLogger.Construction.MessageRaised(Object sender, BuildMessageEventArgs args) in C:\MSBuildStructuredLog\src\StructuredLogger\Construction\Construction.cs:line 394
```

This looks identical and/or similar to some closed issues: https://github.com/KirillOsenkov/MSBuildStructuredLog/issues?q=is%3Aissue+sequence+contains+is%3Aclosed

But it seems I'm running the latest version:

> You have the latest version: 2.1.525

![image](https://user-images.githubusercontent.com/202643/130156659-cb1c3f6b-addb-4530-b633-09cdfc1b5e27.png)

I can share the binlog privately.

**Comment by KirillOsenkov** [comment]
Turns out I misunderstood how `SingleOrDefault()` works :)

I made a fix but I'd still like to see your binlog to understand how this situation can happen.
