### ISSUE TITLE
Unsupported log file format. Latest supported version is 13, the log file has version 14

### ISSUE THREAD

**Issue by yaskovdev** [KirillOsenkov/MSBuildStructuredLog#546]
I am using MSBuild 17.0.0.52104. When I try to open the msbuild.binlog (renamed to `msbuild.binlog.txt` and attached to the ticket below) produced by the `msbuild /bl` command, I get the next exception:

```
System.NotSupportedException: Unsupported log file format. Latest supported version is 13, the log file has version 14.
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream, Progress progress) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 74
   at Microsoft.Build.Logging.StructuredLogger.BinaryLog.ReadBuild(Stream stream, Progress progress, Byte[] projectImportsArchive) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLo
[msbuild.binlog.txt](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/7660489/msbuild.binlog.txt)
g.cs:line 101
   at Microsoft.Build.Logging.StructuredLogger.BinaryLog.ReadBuild(String filePath, Progress progress) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLog.cs:line 41
   at Microsoft.Build.Logging.StructuredLogger.Serialization.Read(String filePath, Progress progress) in C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Serialization.cs:line 71
   at StructuredLogViewer.MainWindow.<>c__DisplayClass29_0.<OpenLogFile>b__2() in C:\MSBuildStructuredLog\src\StructuredLogViewer\MainWindow.xaml.cs:line 407
```

**Comment by yaskovdev** [comment]
[msbuild.binlog.txt](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/7660492/msbuild.binlog.txt)

**Comment by KirillOsenkov** [comment]
Please update the viewer to 2.1.561 (latest). It auto-updates after you restart it.

**Comment by yaskovdev** [comment]
2.1.561 works well. Thank you! I think there is no need to keep the issue open.
