### ISSUE TITLE
NullReferenceException when loading binlog

### ISSUE THREAD

**Issue by rolfbjarne** [KirillOsenkov/MSBuildStructuredLog#561]
Test case:

[log-Build-20220202_162411.binlog.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/7987803/log-Build-20220202_162411.binlog.zip)

Opening on macOS results in (latest Avalonia version as of today):

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Logging.StructuredLogger.MessageProcessor.AddItems(IEnumerable items, TreeNode parent) in C:\projects\msbuildstructuredlog\src\StructuredLogger\Construction\MessageProcessor.cs:line 268
   at Microsoft.Build.Logging.StructuredLogger.MessageProcessor.ProcessTaskParameter(TaskParameterEventArgs args) in C:\projects\msbuildstructuredlog\src\StructuredLogger\Construction\MessageProcessor.cs:line 224
   at Microsoft.Build.Logging.StructuredLogger.MessageProcessor.Process(BuildMessageEventArgs args) in C:\projects\msbuildstructuredlog\src\StructuredLogger\Construction\MessageProcessor.cs:line 37
   at Microsoft.Build.Logging.StructuredLogger.Construction.MessageRaised(Object sender, BuildMessageEventArgs args) in C:\projects\msbuildstructuredlog\src\StructuredLogger\Construction\Construction.cs:line 417
```
<img width="1700" alt="Screen Shot 2022-02-02 at 16 31 22" src="https://user-images.githubusercontent.com/249268/152184930-b991d670-dab9-4cf9-9edc-6fe980e1d30e.png">

Online results:

<img width="1236" alt="Screen Shot 2022-02-02 at 16 31 34" src="https://user-images.githubusercontent.com/249268/152184988-4c32353a-8b51-4ed6-a46e-89a6fee8ba13.png">

**Comment by KirillOsenkov** [comment]
Interesting, this is because in this case it logs a TaskParameterEventArgs with kind SkippedTargetOutputs and null ItemName and Items list:
![image](https://user-images.githubusercontent.com/679326/152250320-2f25cf5c-84a7-4590-b481-f82621178915.png)

Probably need to make a change to MSBuild to not log the event args in the first place.

For now I'll just add a null check in the viewer.

**Comment by KirillOsenkov** [comment]
Found a repro:

```
<Project DefaultTargets="Build">

  <ItemGroup>
    <_CodesignItems Include="foo" />
  </ItemGroup>

  <Target Name="Build">
  </Target>

  <Target Name="Patch" AfterTargets="Build"
          Inputs="@(_CodesignItems)"
          Outputs="@(_CodesignItems -> '%(CodesignStampFile)')">
    <Message Text="foo" />
  </Target>

</Project>
```

**Comment by KirillOsenkov** [comment]
Filed https://github.com/dotnet/msbuild/issues/7362

**Comment by KirillOsenkov** [comment]
I suspect you don't need me to republish the Windows viewer since you're using the Avalonia and the Live one. I'll include this fix with the next batch of fixes and updates.

**Comment by KirillOsenkov** [comment]
@rolfbjarne the `CodesignStampFile` metadata is missing on this item, not sure if intentional:
![image](https://user-images.githubusercontent.com/679326/152253881-b64dea8f-b0a2-4066-b490-c0ccee4614ae.png)

**Comment by rolfbjarne** [comment]
@KirillOsenkov thanks! I was eventually able to figure out that that was the problem, but it's certainly easier when the viewer works :)
