### ISSUE TITLE
Exception immidiately after opening file

### ISSUE THREAD

**Issue by kant2002** [KirillOsenkov/MSBuildStructuredLog#570]
```
System.ArgumentNullException: Value cannot be null.
Parameter name: element
   at MS.Internal.Media.VisualTreeUtils.AsNonNullVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
   at System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

You have the latest version: 2.1.627

It maybe issue with WPF

**Comment by KirillOsenkov** [comment]
does this happen for any binlog or for a specific one? could you email me the problematic binlog? to my first name dot last name at microsoft. Did you try on another computer? did you try on https://live.msbuildlog.com

**Comment by KirillOsenkov** [comment]
@sambent anything jump at you from the stack above?

**Comment by kant2002** [comment]
Also I experience very similar, but slightly different exception with same file, and same conditions
```
System.ArgumentNullException: Value cannot be null.
Parameter name: element
   at MS.Internal.Media.VisualTreeUtils.AsNonNullVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
   at System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
   at System.Windows.Controls.VirtualizingStackPanel.SetAnchorInformation(Boolean isHorizontalOffset)
   at System.Windows.Controls.VirtualizingStackPanel.<>c__DisplayClass94_0.<InitializeViewport>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by SamBent** [comment]
I haven't seen this before.  OnAnchorOperation calls FindScrollOffest twice - once for the (deepest) TreeViewItem at the top of the viewport before the scroll, and once for the topmost element after the scroll.  One of these is null, but neither is supposed to be.  The TreeView layout is getting confused somehow, but I'd need more evidence to figure out how.  A callstack, and even a crash dump, is not enough - as usual the problem is likely to have occurred long before the crash.  In order of preference:  A reliable repro, a time-travel trace, or an STF trace (with matching crash dump).

**Comment by KirillOsenkov** [comment]
@kant2002 if you go to Start Page in the binlog viewer, and disable tree view virtualization, I expect the problems to go away. Could you confirm it?

Also, could you send me that binlog file if possible?

What is the screen DPI of that monitor? More than 100%? How many monitors do you have and what’s the screen resolution?

**Comment by kant2002** [comment]
> @kant2002 if you go to Start Page in the binlog viewer, and disable tree view virtualization, I expect the problems to go away. Could you confirm it?

@KirillOsenkov I confirm that issue goes away.

> Also, could you send me that binlog file if possible?

Unless your email has one L instead of two, or youg github handle does not reflect your name, you should have email with file attached.

> What is the screen DPI of that monitor? More than 100%? How many monitors do you have and what’s the screen resolution?

One external monitor attached to laptop. DPI = 100% (I assume this is Scale And Layout in the Home -> Display section in the System Settings), resolution 1920x1080

**Comment by KirillOsenkov** [comment]
I got the binlog, thanks! Unfortunately it works just fine on my machine. I'll try a few other things too.

Meanwhile, if you have time, could you please try to record scrollTrace.stf as described here:
https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/21#issuecomment-514701904

We had a couple similar issues:
https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/407
https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/21

**Comment by kant2002** [comment]
Send STF file to same location. Anything else what I can do?
