### ISSUE TITLE
COMException when Log viewer open and reconnect to RDP

### ISSUE THREAD

**Issue by erinlah-ms** [KirillOsenkov/MSBuildStructuredLog#614]
Received an unexpected exception dialog in the following situation. I had msbuild structured log viewer open on machine B, and a long running RDP session (2+ days?) from machine A to machine B. I closed the RDP session to machine B, and reconnected RDP from machine A to machine B. Upon logging in, my msbuild structured log viewer instance was displaying an exception dialog with the following text:

```
---------------------------

---------------------------
Unexpected exception. Sorry about that.
Please Ctrl+C to copy this text and file an issue at https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new

System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------
```

Both machine A and machine B are running Windows 11, Version 21H2 (OS Build 22000.795).
Machine A is a native installation of Windows 11.
Machine B is a virtual machine, hosted on machine A.
Netfx version on Machine B is 4.8.4510.0

**Comment by KirillOsenkov** [comment]
Thanks for logging this. We've been seeing a bunch of intermittent exceptions in DUCE.Channel.SyncFlush() over the years in various WPF apps (including Visual Studio). No idea how to go about this, but it's nice to have it logged. If I think of anything, I'll come back here.
