### ISSUE TITLE
Investigate "Should not waste a dictionary in Clone Metadata when no metadata is present"

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#65]
MSBuild has an assert, investigate that and log a bug if necessary

**Comment by KirillOsenkov** [comment]
We should not waste a dictionary for no metadata

**Comment by KirillOsenkov** [comment]
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
We should not waste a dictionary for no metadata
 
 
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.CopyMetadataTo(ITaskItem destinationItem, Boolean addOriginalItemSpec) in C:\msbuild\src\XMakeBuildEngine\Instance\ProjectItemInstance.cs:line 1348
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem..ctor(TaskItem source, Boolean addOriginalItemSpec) in C:\msbuild\src\XMakeBuildEngine\Instance\ProjectItemInstance.cs:line 838
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.DeepClone() in C:\msbuild\src\XMakeBuildEngine\Instance\ProjectItemInstance.cs:line 1708
   at Microsoft.Build.BackEnd.Logging.TargetLoggingContext.TargetOutputItemsInstanceEnumeratorProxy.<GetEnumerator>d__2.MoveNext() in C:\msbuild\src\XMakeBuildEngine\BackEnd\Components\Logging\TargetLoggingContext.cs:line 159
   at Microsoft.Build.BackEnd.LogMessagePacket.TranslateTargetFinishedEvent(INodePacketTranslator translator, TargetFinishedEventArgs finishedEvent) in C:\msbuild\src\XMakeBuildEngine\BackEnd\Components\Communications\LogMessagePacket.cs:line 64
   at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(INodePacketTranslator translator) in C:\msbuild\src\Shared\LogMessagePacketBase.cs:line 295
   at Microsoft.Build.Shared.LogMessagePacketBase.Translate(INodePacketTranslator translator) in C:\msbuild\src\Shared\LogMessagePacketBase.cs:line 255
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.PacketPumpProc() in C:\msbuild\src\Shared\NodeEndpointOutOfProcBase.cs:line 527
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
 
---------------------------
Abort   Retry   Ignore  
---------------------------

**Comment by KirillOsenkov** [comment]
This is probably stale by now
