### ISSUE TITLE
Issue with NotSupportedException

### ISSUE THREAD

**Issue by FabrizioVitale** [KirillOsenkov/MSBuildStructuredLog#679]
---------------------------

---------------------------
Error while analyzing build. Sorry about that. Please Ctrl+C to copy this text and file an issue on https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new 

System.NotSupportedException: The given path's format is not supported.

   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)

   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)

   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)

   at Microsoft.Build.Logging.StructuredLogger.DoubleWritesAnalyzer.<>c.<IsDoubleWrite>b__8_0(String f) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\DoubleWritesAnalyzer.cs:line 111

   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()

   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)

   at Microsoft.Build.Logging.StructuredLogger.DoubleWritesAnalyzer.IsDoubleWrite(KeyValuePair`2 bucket) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\DoubleWritesAnalyzer.cs:line 110

   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()

   at Microsoft.Build.Logging.StructuredLogger.DoubleWritesAnalyzer.AppendDoubleWritesFolder(Build build) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\DoubleWritesAnalyzer.cs:line 27

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.PostAnalyzeBuild(Build build) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\BuildAnalyzer.cs:line 210

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.ProcessAfterChildrenVisited(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\BuildAnalyzer.cs:line 186

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Analyze() in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\BuildAnalyzer.cs:line 70

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeBuild(Build build) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\BuildAnalyzer.cs:line 48

   at StructuredLogViewer.MainWindow.<>c__DisplayClass30_0.<QueueAnalyzeBuild>b__0() in C:\MSBuildStructuredLog\src\StructuredLogViewer\MainWindow.xaml.cs:line 457
---------------------------
OK   
---------------------------

**Comment by KirillOsenkov** [comment]
Thanks for reporting!
