### ISSUE TITLE
Can't open binlog which uses paired macOS to perform some of the build steps

### ISSUE THREAD

**Issue by pavel-faltynek** [KirillOsenkov/MSBuildStructuredLog#726]
```
---------------------------

---------------------------
Error while analyzing build. Sorry about that. Please Ctrl+C to copy this text and file an issue on https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new 

System.NotSupportedException: The given path's format is not supported.

   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)

   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)

   at Microsoft.Build.Logging.StructuredLogger.FileCopyMap.AnalyzeCopyOperation(FileCopyOperation copyOperation, Task task) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\FileCopyMap.cs:line 105

   at Microsoft.Build.Logging.StructuredLogger.FileCopyMap.AnalyzeCopyTask(CopyTask copyTask) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\FileCopyMap.cs:line 76

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeTask(Task task) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\BuildAnalyzer.cs:line 363

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\BuildAnalyzer.cs:line 110

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\BuildAnalyzer.cs:line 113

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\BuildAnalyzer.cs:line 113

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\BuildAnalyzer.cs:line 113

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Analyze() in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\BuildAnalyzer.cs:line 87

   at Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeBuild(Build build) in C:\MSBuildStructuredLog\src\StructuredLogger\Analyzers\BuildAnalyzer.cs:line 51

   at StructuredLogViewer.MainWindow.<>c__DisplayClass34_0.<QueueAnalyzeBuild>b__0() in C:\MSBuildStructuredLog\src\StructuredLogViewer\MainWindow.xaml.cs:line 577
---------------------------
OK   
---------------------------
```

**Comment by pavel-faltynek** [comment]
Might it be because there are unix like paths present in the log?

**Comment by KirillOsenkov** [comment]
Any change you could email your binlog privately to me at kirill dot osenkov at microsoft? Don't do it if it contains secrets.

I think I know how to fix this (avoid using Path.GetFullPath() there), but would be nice to confirm the fix. Alternatively I can push the fix blindly and you can build the latest version locally and test it yourself.

**Comment by KirillOsenkov** [comment]
I made a fix, you could try clone the repo, build using `msbuild /r /m /bl StructuredLogViewer.sln` and then run `bin\StructuredLogViewer\Debug\net472\StructuredLogViewer.exe` and see if it fixes it.
