### ISSUE TITLE
Failure to open binlog on first attempt

### ISSUE THREAD

**Issue by JustinSchneiderPBI** [KirillOsenkov/MSBuildStructuredLog#734]
Filing as requested! It blocked me opening the binlog on my first attempt. No problem the second time.
---------------------------

---------------------------
Unexpected exception. Sorry about that.
Please Ctrl+C to copy this text and file an issue at https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new

System.ComponentModel.Win32Exception (0x80004005): Invalid monitor handle
   at System.Windows.Window.TransformWorkAreaScreenArea(Point pt, TransformType transformType)
   at System.Windows.Window.GetNormalRectDeviceUnits(IntPtr hwndHandle)
   at System.Windows.Window.GetNormalRectLogicalUnits(IntPtr hwndHandle)
   at System.Windows.Window.UpdateDimensionsToRestoreBounds()
   at System.Windows.Window.WmSizeChanged(IntPtr wParam)
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by JustinSchneiderPBI** [comment]
Popped up again when my machine went to sleep. 2 instances of the error. I have multiple binlogs open from yesterday atm, and I did not open any new one today. Doesn't seem to be blocking, though I'm not working on these atm.

**Comment by KirillOsenkov** [comment]
I think it tries to restore window position from a different monitor configuration and crashing, perhaps a try/catch is missing somewhere
